// Generated by .github/workflows/build-entry-lists.yml — do not edit by hand.
// Add or remove a file in entries/ and this list rebuilds on push.
const entryFiles = [
    "entries/prototype-1.js",
];
