// Generated by .github/workflows/build-entry-lists.yml — do not edit by hand.
// Add or remove a file in entries/ and this list rebuilds on push.
const newsFiles = [
    "entries/alcertha-early-work.js",
    "entries/logistics-empire-paused.js",
    "entries/site-is-live.js",
    "entries/site-refresh.js",
    "entries/strataforge-idle-prototype.js",
];
